import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const colorConfig: { [key: string]: string } = {
  "#f44336": "#ff7961",
  "#e91e63": "#ff6090",
  "#9c27b0": "#d05ce3",
  "#673ab7": "#9a67ea",
  "#3f51b5": "#757de8",
  "#2196f3": "#6ec6ff",
  "#03a9f4": "#67daff",
  "#00bcd4": "#62efff",
  "#009688": "#52c7b8",
  "#4caf50": "#80e27e",
  "#8bc34a": "#bef67a",
  "#cddc39": "#ffff6e",
  "#ffeb3b": "#ffff72",
  "#ffc107": "#fff350",
  "#ff9800": "#ffc947",
  "#ff5722": "#ff8a50",
  "#795548": "#a98274",
  "#607d8b": "#8eacbb",
};
